### PR TITLE
Add relative names and imports

### PR DESCRIPTION
**Pull request by felipegchi**
I'm not sure if the code is good enough so i'm going to find ways to improve it without having to modify the AST type. 

Now top-level definitions and variables can use relative identifiers and aliases to make names shorter e.g:

A/B/c.kind2
```
// Instead of writing "A.B.c : ..." we can simply use the current folder operator "/". 
/c : U60
/c = ./d // We can navigate back using dots in front of the slash

// I'm defining this function in the previous folder (I navigated back using the 
// dot in front of the slash) so the absolute name of the function is "A.d"
./d : U60
./d = 2 
```

main.kind2
```
// I can make an alias like that
use A.B as C

Main : U60
Main = C/c // Instead of a dot, we use the backslash to use the alias.
```

### CODE REVIEW

**Comment by developedby** [comment]
I really don't like that `.` in absolute paths means "go forward" and in relative paths it means "go back"

**Comment by developedby** [comment]
If we're going with `.` and `/`, why not just use unix convention?
`/name1/name2/name3` for an absolute path
`./name1/name2/name3` or `name1/name2/name3` for a relative path

**Comment by developedby** [comment]
Personally, I don't think relative paths are even needed, a `use User.developedby.LibWithALargeName as mylib` already covers basically every use case.
I also don't think having a different syntax for non-absolute paths is needed. It's reasonable to expect the user to know what names they aliased in the beginning of a file and it's cheap for the parser/compiler/etc to resolve these paths even if they use the same syntax as absolute paths. To me there isn't any real advantage to making this distinction.

**Comment by VictorTaelin** [comment]
The structure of the code looks good to me. 

I think relative paths are important, though, because if you have multiple small files in a long sub-namespace, then `use` might start getting overwhelming. For example:

```
// Apps.AcademyOfCats.Board.Map.Restricted.get_range.kind2

use Apps.AcademyOfCats.Board.Map as Map
use Apps.AcademyOfCats.Board.Map.Unrestricted as UMap
use Apps.AcademyOfCats.Board.Map.Vec as Vec
use Apps.AcademyOfCats.Board.Map.Result as Res
use Apps.AcademyOfCats.Board.Entity as Ent

/get_range (map: Map/) (from: Vec/) (to: Vec/) : Res/ (List Ent/)
/get_range map from to = UMap/get_range map from to
```

VS

```
// Apps.AcademyOfCats.Board.Map.Restricted.get_range.kind2

/get_range (map: ../Map) (from: ../Vec) (to: ../Vec) : ../Res (List .../Ent)
/get_range map from to = ./Unrestricted.get_range map from to
```

The point is that `use` works well when you have a small list-of-imports vs size-of-file ratio, but if the size of the file itself is small, then the imports become substantial noise.

**Comment by developedby** [comment]
I agree with most of your points, but I still don't see the need for using `/`.

Why not write `.name` for a relative name in the same folder, `..name` for a relative name in a folder above and `.name1.name1` for a relative name one folder down?

Also why not just shadow names by default? If the user conciously chose to use `Map` as the alias for their structure I think it's fine if they can't access the base `Map` anymore, they're the ones that chose that name so I don't think there'll ever be any confusion.

**Comment by VictorTaelin** [comment]
Why create conflicts when we can *not* create conflicts? Is it something about the aesthetics of the `/` symbol in particular? I don't get it. I think using `/` is a good idea precisely because it doesn't conflict with anything, it becomes a symbol with a well-defined semantics (it expends to a larger name) and there is no risk someone will use `Map`, then realize they actually want the base `Map` and need to rename everything. Also I really like the clarity aspect of being able to read a name and know what it refers to. If I read `Map.get` in a file, I know it refers to `Map/get.kind2`, I can assume that in a glance, no need to also look the import list to be sure it isn't anything else.

**Comment by developedby** [comment]
Because having two different syntaxes for referring to names is annoying, adds to the list of things you have to keep in mind at all times when writing/reading code and creates a lot of opportunities for making mistakes.

I'd also argue that if you have a relative `Map` you definitely don't want to have an absolute `Map` at the same time. Just imagine a code like
```
let name = Map.get base_map "key"
let my_map = Map/set my_map "key" name
```
Super confusing and error-prone.

**Comment by VictorTaelin** [comment]
Okay, let's remove the relative imports and keep qualified imports. But I then agree with you both that you should be able to shorten names in the same file. Can we do it?

```
use Foo.Bar.Map as M

causes

M/name

to expand t o

Foo.Bar.Map.name
```

And

```
top_level_definition

causes

to_level_definition

to expand to

Full.File.Expansion.top_level_definition
```

**Pull request closed without merging**
